server:
  compression:
    enabled: true
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vetero?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: superSecretPassword
    initialization-mode: always
